INSERT INTO PROXY_PROPS(ID, ENABLED, PORT, HOST) values ('1', false, 8008, '127.0.0.1');
INSERT INTO PROXY_PROPS(ID, ENABLED, PORT, HOST) values ('2', false, 8008, '127.0.0.1');
INSERT INTO PROXY_CONFIG(ID, HTTPPROPS_ID, HTTPSPROPS_ID) values('1' , '1', '2');
