{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    {{- if .Values.certmanager.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.certmanager.cluster_issuer }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.class }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.prefix }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: {{ .Values.service.port }}
{{- if .Values.certmanager.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.host }}-tls
{{- end }}
{{- end }}
